## Applying Energy Path algtm to road photos

In [1]:
import cv2
import numpy as np
import matplotlib as plt

In [2]:
RED = (0, 0, 255)

MAX_ROAD_WIDTH = 275
MAX_ROAD_X = 175

MIN_ROAD_WIDTH = 75
MIN_ROAD_X = 25

In [3]:
img = cv2.imread("C:\Programs/facultate/licenta/my-autonomous-car/resources/fullCurve.png")

IMG_WIDTH = img.shape[1]
IMG_HEIGHT = img.shape[0]

In [4]:
print(img)

[[[207 212 209]
  [220 225 222]
  [224 230 225]
  ...
  [104 109 108]
  [107 111 111]
  [111 116 115]]

 [[201 207 203]
  [224 230 226]
  [222 228 223]
  ...
  [175 180 179]
  [175 180 179]
  [174 179 178]]

 [[181 187 184]
  [227 232 229]
  [224 230 225]
  ...
  [185 189 189]
  [183 188 187]
  [181 186 185]]

 ...

 [[ 66  70  64]
  [ 66  70  64]
  [ 66  70  64]
  ...
  [ 56  60  56]
  [ 56  60  55]
  [ 56  60  55]]

 [[ 66  70  64]
  [ 66  70  64]
  [ 66  70  64]
  ...
  [ 56  60  56]
  [ 56  60  55]
  [ 56  60  55]]

 [[ 66  70  64]
  [ 66  70  64]
  [ 66  70  64]
  ...
  [ 56  60  56]
  [ 56  60  55]
  [ 56  60  55]]]


In [5]:

cv2.imshow("original",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [6]:
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

cv2.imshow("gray",gray)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Gaussian Blur

In [7]:
blurred = cv2.GaussianBlur(gray,(3,3),3)

cv2.imshow("blurred",blurred)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Bilateral blur


In [8]:
bilateralBlurred = cv2.bilateralFilter(gray, 11, 21, 7)

cv2.imshow("bilateral Blurred",bilateralBlurred)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [9]:
blurred = cv2.GaussianBlur(gray,(3,3),3)
bilateralBlurred = cv2.bilateralFilter(gray, 11, 21, 7)

cv2.imshow("bilateral Blurred",bilateralBlurred)


cv2.imshow("blurred",blurred)

cv2.waitKey(0)
cv2.destroyAllWindows()

### Classic binary thresholding

In [10]:
_, threshClassis = cv2.threshold(blurred, 170, 255, cv2.THRESH_BINARY)
# cv2.imwrite("classicTresh.jpg",threshClassis)
cv2.imshow("classic thresh",threshClassis)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Otsu's thresholding

In [11]:
T, threshOtsu = cv2.threshold(blurred, 0, 255, cv2.THRESH_BINARY | cv2.THRESH_OTSU)
# cv2.imwrite("classicTresh.jpg",threshClassis)
print(T)
cv2.imshow("classic thresh",threshOtsu)
cv2.waitKey(0)
cv2.destroyAllWindows()

137.0


### Adaptive binary thresholding

In [12]:
threshAdap = cv2.adaptiveThreshold(blurred, 255,
	cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY_INV, 5, 10)

cv2.imshow("adaptive thresh",threshAdap)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [13]:
blurred = cv2.GaussianBlur(gray,(5,5),0)
# blurred = cv2.equalizeHist(blurred)

# threshAdap = cv2.adaptiveThreshold(blurred, 255,
#     cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY_INV, 11, 2)
_, threshClassis = cv2.threshold(blurred, 170, 255, cv2.THRESH_BINARY)
kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (3, 3))
closed = cv2.morphologyEx(threshClassis, cv2.MORPH_OPEN, kernel)
cv2.imshow("blurred",closed)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Morphological ops

In [14]:
kernel = np.ones((5,5),np.uint8)
closing = cv2.morphologyEx(threshClassis, cv2.MORPH_CLOSE, kernel)
cv2.imshow("closed img",closing)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [15]:
kernel = np.ones((3,3),np.uint8)
opening = cv2.morphologyEx(threshClassis, cv2.MORPH_OPEN, kernel)
cv2.imshow("opened img",opening)
cv2.waitKey(0)
cv2.destroyAllWindows()

### TESTS

In [16]:
_, threshClassis = cv2.threshold(blurred, 185, 255, cv2.THRESH_BINARY)
# kernel = np.ones((3,3),np.uint8)
kernel = cv2.getGaussianKernel(5,5)
closing = cv2.morphologyEx(threshClassis, cv2.MORPH_CLOSE, kernel)
opening = cv2.morphologyEx(threshClassis, cv2.MORPH_OPEN, kernel)

# cv2.imwrite("classicTresh.jpg",threshClassis)
cv2.imshow("classic thresh",threshClassis)
cv2.imshow("opened img",opening)
cv2.imshow("closed img",closing)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [17]:
blurred = cv2.GaussianBlur(gray,(3,3),0)
cv2.imshow("blur clasic img",blurred)
bilateralBlurred = cv2.bilateralFilter(gray, 11, 21, 7)
cv2.imshow("blur bilateral img",bilateralBlurred)
_, threshClassis = cv2.threshold(blurred, 185, 255, cv2.THRESH_BINARY)
cv2.imshow("thresh clasic  + blurimg",threshClassis)
_, threshClassis = cv2.threshold(bilateralBlurred, 185, 255, cv2.THRESH_BINARY)
cv2.imshow("thresh clasic + biblur img",threshClassis)
kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (15, 15))
closing = cv2.morphologyEx(threshClassis, cv2.MORPH_CLOSE, kernel)
cv2.imshow("closed img",closing)
kernel1 = np.ones((3,3),np.uint8)
opening = cv2.morphologyEx(threshClassis, cv2.MORPH_OPEN, kernel1)
# cv2.imshow("opened img",opening)
kernel2 = np.ones((3,3),np.uint8)
opening = cv2.morphologyEx(closing, cv2.MORPH_OPEN, kernel2)
# cv2.imshow("both img",opening)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Gradient making

In [18]:
def compute_energy(img):
    """
    calculeaza energia la fiecare pixel pe baza gradientului
    :param img: imaginea initiala
    :return:E - energia
    """
    # urmati urmatorii pasi:
    # 1. transformati imagine in grayscale
    # 2. folositi filtru sobel pentru a calcula gradientul in directia X si Y
    # 3. calculati magnitudinea pentru fiecare pixel al imaginii
    E = np.zeros((img.shape[0],img.shape[1]))
    # img_grey = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    grad_x = cv2.Sobel(img,ddepth=cv2.CV_16S,dx=1,dy=0)
    grad_y = cv2.Sobel(img,ddepth=cv2.CV_16S,dx=0,dy=1)

    abs_x = np.abs(grad_x)
    abs_y = np.abs(grad_y)

    E = abs_x + abs_y

    return E

In [19]:
def compute_energy_v2(img):
    ksize = 3

    gX = cv2.Sobel(img, ddepth=cv2.CV_32F, dx=1, dy=0, ksize=ksize)
    gY = cv2.Sobel(img, ddepth=cv2.CV_32F, dx=0, dy=1, ksize=ksize)

    gX = cv2.convertScaleAbs(gX)
    gY = cv2.convertScaleAbs(gY)

    # combined = cv2.addWeighted(gX, 0.5, gY, 0.5, 0)

    magnitude = np.sqrt((gX ** 2) + (gY ** 2))
    # magnitude = gX + gY

    return magnitude


In [20]:
combined = compute_energy_v2(threshClassis)

# cv2.imshow("pre", pre)
# cv2.imshow("Sobel/Scharr Combined", combined)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [21]:
gradient = compute_energy(opening)
cv2.imshow("gradient img",gradient)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [22]:
def select_dynamic_programming_path_going_up(E):
    M = np.zeros(E.shape)
    M[0,:] = E[0,:]
    for i in range(1,E.shape[0]):
        for j  in range (E.shape[1]):
            if j == 0:
                M[i][j] = E[i,j]+max(M[i-1,0],M[i-1,1])
            elif j == E.shape[1] - 1:
                M[i,j] = E[i,j]+max(M[i-1,j],M[i-1,j-1])
            else:
                M[i,j] = E[i,j]+max(M[i-1,j+1],M[i-1,j],M[i-1,j-1])
    line = M.shape[0] - 1
    col = np.argmax(M[line,:])
    # print(np.max(M[line,:]))
    path = [0 for i in range(line+1)]

    path[line] = (line,col)
    
    for line in range(M.shape[0]-2,-1,-1):
        if col == 0:
            if M[line,0] < M[line,1]:
                new_col = 1
            else:
                new_col = 0
        elif col == E.shape[1] - 1:
            if M[line,col] < M[line,col-1]:
                new_col = col - 1
            else:
                new_col = col
        else:
            neigh = np.array([M[line,col-1],M[line,col],M[line,col+1]])
            new_col = col+np.argmax(neigh) - 1

        path[line]= (line,new_col)

        col = new_col

    return path

In [23]:
def select_dynamic_programming_path_going_sideways(E):
    M = np.zeros(E.shape)
    M[0,:] = E[0,:]
    for i in range(1,E.shape[0]):
        for j  in range (E.shape[1]):
            if j == 0:
                M[i][j] = E[i,j]+max(M[i-1,0],M[i-1,1])
            elif j == E.shape[1] - 1:
                M[i,j] = E[i,j]+max(M[i-1,j],M[i-1,j-1])
            else:
                M[i,j] = E[i,j]+max(M[i-1,j+1],M[i-1,j],M[i-1,j-1],M[i][j+1],M[i][j-1])
    line = M.shape[0] - 1
    col = np.argmax(M[line,:])
    # print(np.max(M[line,:]))
    path = [0 for _ in range(60)]
    # path = []
    index = 0

    path[index] = (line,col)

    lineIndex = M.shape[0]-1
    nextLine = False
    while lineIndex > 0 and col >= 0 and col < M.shape[1] and index != 50:
        if col == 0:
            # if M[lineIndex,0] < M[lineIndex,1]:
            #     new_col = 1
            #     nextLine = False
            # else:
            #     new_col = 0
            #     nextLine = False
            if M[lineIndex-1,0] < M[lineIndex-1,1]:
                new_col = 1
                nextLine = True
            else:
                new_col = 0
                nextLine = True
        elif col == E.shape[1] - 1:
            if M[lineIndex-1,col] < M[lineIndex-1,col-1]:
                new_col = col - 1
                nextLine = True
            else:
                new_col = col
                nextLine = True
        else:
            same_line = np.array([M[lineIndex,col-1],M[lineIndex,col+1]])
            upper_line = np.array([M[lineIndex-1,col-1],M[lineIndex-1,col],M[lineIndex-1,col+1]])
            if np.max(same_line) > np.max(upper_line):
                new_col = col+np.argmax(same_line) - 1
                nextLine = False
            else:
                new_col = col+np.argmax(upper_line) - 1
                nextLine = True

        if nextLine:
            lineIndex -= 1

        index += 1  
        path[index]= (lineIndex,new_col)

        col = new_col
    
    return path

In [24]:
dtype = [('x', 'uint16'), ('y', 'uint16')]  # specifying tuple structure as a list of pairs
np_array_of_tuples = np.zeros(10, dtype=dtype)
np_array_of_tuples

array([(0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0), (0, 0),
       (0, 0), (0, 0)], dtype=[('x', '<u2'), ('y', '<u2')])

In [25]:
def select_dynamic_programming_border_going_up_point_start(E,point): #TODO Sa incerc sa tin pathul in interiorul benzii si sa nu fac pe 2 imagini diferite    
    M = np.zeros(E.shape)
    M[0,:] = E[0,:]
    for i in range(1,E.shape[0]):
        for j  in range (E.shape[1]):
            if j == 0:
                M[i][j] = E[i,j]+max(M[i-1,0],M[i-1,1])
            elif j == E.shape[1] - 1:
                M[i,j] = E[i,j]+max(M[i-1,j],M[i-1,j-1])
            elif j >= 2 and j <= E.shape[1] - 3:
                M[i,j] = E[i,j]+max(M[i-1,j+1],M[i-1,j],M[i-1,j-1],M[i-1,j-2],M[i-1,j+2])
            else:
                M[i,j] = E[i,j]+max(M[i-1,j+1],M[i-1,j],M[i-1,j-1])
    line = M.shape[0] - 1
    # col = np.argmax(M[line,:])
    col = point
    # print(np.max(M[line,:]))
    # path = [(0,0) for i in range(line+1)]

    dtype = [('x', 'uint16'), ('y', 'uint16')]
    path = np.zeros(line+1, dtype=dtype)

    path[line] = (line,point)

    direction = point
    
    for line in range(M.shape[0]-2,60,-1):
        if col == 0:
            if M[line,0] < M[line,1]:
                new_col = 1
            else:
                new_col = 0
        elif col == E.shape[1] - 1:
            if M[line,col] < M[line,col-1]:
                new_col = col - 1
            else:
                new_col = col
        elif col >= 2 and col <= E.shape[1] - 3:
            if not (M[line,col-1] == M[line,col] == M[line,col+1] == M[line,col-2] == M[line,col+2]):
                neigh = np.array([M[line,col-2],M[line,col-1],M[line,col],M[line,col+1],M[line,col+2]]) #TODO proiectia parcursului actual al masinii cu unghiul actual al rotilor
                new_col = col+np.argmax(neigh) - 2
            else:
                new_col = col - (direction - col)
                # new_col = col
                # if M[line,new_col] == 0 and new_col > 0:
                #     new_col -= 1
        else:
            if not (M[line,col-1] == M[line,col] == M[line,col+1]):
                neigh = np.array([M[line,col-1],M[line,col],M[line,col+1]]) #TODO proiectia parcursului actual al masinii cu unghiul actual al rotilor
                new_col = col+np.argmax(neigh) - 1
            else:
                new_col = col - (direction - col)
        # if col - 1 > 1 and col + 1 < E.shape[1] - 2:
        #     print(M[line,col-2],M[line,col-1],M[line,col],M[line,col+1],M[line,col+2],end=" ")
        #     print(line,end=" ")
        #     print(new_col)
        direction = col

        path[line]= (line,new_col)

        col = new_col

    return path

### Draw on image

In [26]:
def draw_path(img, path, color):
    
    new_image = img.copy()

    for row, col in path:
        if col and col < img.shape[1]:
            new_image[row, col] = color
            
    return new_image

### Preprocess image

In [27]:
def preprocess(img):
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    blurred = cv2.GaussianBlur(gray,(3,3),0)

    _, threshClassis = cv2.threshold(blurred, 190, 255, cv2.THRESH_BINARY)
    
    # kernel = cv2.getStructuringElement(cv2.MORPH_DILATE, (15, 15))
    # closing = cv2.morphologyEx(threshClassis, cv2.MORPH_CLOSE, kernel)

    return threshClassis


In [28]:
pre = preprocess(img)
preL = pre[:,:int(pre.shape[1]/2)]
preR = pre[:,int(pre.shape[1]/2):]
cv2.imshow('PreR', preR)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [29]:
pre = preprocess(img)
grad = compute_energy(pre)
cv2.imshow('Pre', pre)
cv2.imshow('grad', grad)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Histogram

In [30]:
def get_lane_start(img):
    histogram = np.sum(img[img.shape[0] // 2:, :], axis = 0)

    midpoint = int(histogram.shape[0] / 2)

    leftxBase = np.argmax(histogram[:midpoint])
    rightxBase = np.argmax(histogram[midpoint:]) + midpoint

    return leftxBase,rightxBase

### Bordering going always up

In [31]:
def find_borders(preprocImg):
    
    leftxBase,rightxBase = get_lane_start(preprocImg)

    preprocImg[:20,:] = 0

    gradientImg = compute_energy_v2(preprocImg)

    borderL = select_dynamic_programming_border_going_up_point_start(gradientImg,leftxBase)
    borderR = select_dynamic_programming_border_going_up_point_start(gradientImg,rightxBase)
    # print(pathL)
    # print(pathR)

    return borderL,borderR

In [32]:
def find_width(y):
    return w1 + (MIN_ROAD_WIDTH - MAX_ROAD_WIDTH) / (min - y1) * (y - y1)

In [33]:
def find_path(borderL,borderR):
    for yL,yR in zip(borderL,borderR):
        if yR[1] - yL[1] < MIN_ROAD_WIDTH:
            if yL[1] > IMG_WIDTH//2:
                yL[1] = 0
                yR[1] += 0
            elif yR[1] <  IMG_WIDTH //2:
                yR[1] = 0
    # path[:, 1] = np.where(path[:, 1] < 240, 0, path[:, 1])
    path = np.array([(x, (yR + yL)//2) for (x, yL), (_, yR) in zip(borderL, borderR)])
    
    return path

In [34]:
def determine_deviation_simple(path,img):

    lane_center_x = (path[-1][0],path[0][0])
    # lane_center_x[1] = path[-1][0]

    lane_center_y = (path[-1][1],path[0][1])
    # lane_center_y[1] = path[-1][1]

    car_position = (160, 240)  # Car's position (x_c, y_c)
    car_heading = (1, 1)

    car_direction_end = (
        int(car_position[0] + car_heading[0] * 100),
        int(car_position[1] + car_heading[1] * 100),
    )

    print(lane_center_x)

    lane_start = (int(lane_center_x[0]), int(lane_center_y[0]))
    lane_end = (int(lane_center_x[-1]), int(lane_center_y[-1]))

    print(lane_start,lane_end)

    cv2.line(img, (0,0), (100,100), color=(0, 255, 255), thickness=1)

    # cv2.line(img, car_position, car_direction_end, color=(0, 0, 255), thickness=2)

    # Draw the car's position
    # cv2.circle(img, car_position, radius=5, color=(0, 255, 0), thickness=-1)

    return img

In [39]:
image = cv2.imread("fullNewTrack.jpg")
preprocImg = preprocess(image)

borderL,borderR = find_borders(preprocImg)
# for yL,yR in zip(borderL,borderR):
#     print(yR)
borderedImgL = draw_path(image,borderL,RED)
borderedImg = draw_path(borderedImgL,borderR,RED)

path = find_path(borderL,borderR)
# print(path)
filtered_path = path[~np.all(path == 0, axis=1)]
print(filtered_path)
pathImg = draw_path(image,path,RED)
# determine_deviation_simple(path,img)
imgCopy = image.copy()
imgDirection = determine_deviation_simple(filtered_path,imgCopy)
cv2.imshow('imgDirection', imgDirection)
# cv2.imwrite("testStraight.jpg",borderedImg)
cv2.imshow('pathImg', pathImg)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[ 61 231]
 [ 62 231]
 [ 63 231]
 [ 64 231]
 [ 65 232]
 [ 66 232]
 [ 67 232]
 [ 68 232]
 [ 69 232]
 [ 70 233]
 [ 71 232]
 [ 72 232]
 [ 73 233]
 [ 74 233]
 [ 75 233]
 [ 76 234]
 [ 77 234]
 [ 78 234]
 [ 79 234]
 [ 80 234]
 [ 81 235]
 [ 82 235]
 [ 83 235]
 [ 84 235]
 [ 85 235]
 [ 86 236]
 [ 87 236]
 [ 88 236]
 [ 89 236]
 [ 90 237]
 [ 91 237]
 [ 92 237]
 [ 93 238]
 [ 94 238]
 [ 95 238]
 [ 96 238]
 [ 97 238]
 [ 98 239]
 [ 99 239]
 [100 239]
 [101 239]
 [102 240]
 [103 240]
 [104 240]
 [105 240]
 [106 240]
 [107 241]
 [108 241]
 [109 241]
 [110 242]
 [111 241]
 [112 242]
 [113 242]
 [114 242]
 [115 242]
 [116 242]
 [117 243]
 [118 243]
 [119 243]
 [120 243]
 [121 243]
 [122 243]
 [123 243]
 [124 243]
 [125 244]
 [126 244]
 [127 244]
 [128 244]
 [129 245]
 [130 245]
 [131 245]
 [132 245]
 [133 245]
 [134 246]
 [135 246]
 [136 246]
 [137 246]
 [138 246]
 [139 246]
 [140 246]
 [141 247]
 [142 247]
 [143 247]
 [144 247]
 [145 247]
 [146 247]
 [147 248]
 [148 248]
 [149 248]
 [150 248]
 [151 248]

## Video Test

In [40]:
cap = cv2.VideoCapture('newCameraRodNewTrack.mp4')
 
while cap.isOpened():
    ret, frame = cap.read()
 
    # if frame is read correctly ret is True
    if not ret:
        print("Can't receive frame (stream end?). Exiting ...")
        break
    
    # pre = preprocess(frame)
    # leftxBase,rightxBase = get_lane_start(pre)
    # pre[:20,:] = 0
    # cv2.imshow("grad Image",pre)
    # grad = compute_energy_v2(pre)
    # pathL = select_dynamic_programming_border_going_up_point_start(grad,leftxBase)
    # pathR = select_dynamic_programming_border_going_up_point_start(grad,rightxBase)
    # path = find_path(borderL,borderR)
    # new_img = draw_path(frame,pathL,pathR,RED) 
    # cv2.imshow('newImg', new_img)

    preprocImg = preprocess(frame)
    cv2.imshow('preprocImg', preprocImg)

    borderL,borderR = find_borders(preprocImg) 
    # for yL,yR in zip(borderL,borderR):
    #     print(yR)
    borderedImgL = draw_path(frame,borderL,RED)
    borderedImg = draw_path(borderedImgL,borderR,RED)

    path = find_path(borderL,borderR)
    # print(path)
    pathImg = draw_path(borderedImg,path,RED)
    # cv2.imshow('borderedImg', borderedImg)
    # cv2.imwrite("testStraight.jpg",borderedImg)
    cv2.imshow('pathImg', pathImg)
    direction = determine_deviation_simple(path,frame)
    # cv2.imshow('direction', direction)
    
    if cv2.waitKey(1) == ord('q'):
        break
 
cap.release()
cv2.destroyAllWindows()

(np.uint16(479), np.uint16(0))
(479, 318) (0, 0)
(np.uint16(479), np.uint16(0))
(479, 318) (0, 0)
(np.uint16(479), np.uint16(0))
(479, 318) (0, 0)
(np.uint16(479), np.uint16(0))
(479, 318) (0, 0)
(np.uint16(479), np.uint16(0))
(479, 318) (0, 0)
(np.uint16(479), np.uint16(0))
(479, 318) (0, 0)
(np.uint16(479), np.uint16(0))
(479, 318) (0, 0)
(np.uint16(479), np.uint16(0))
(479, 318) (0, 0)
(np.uint16(479), np.uint16(0))
(479, 318) (0, 0)
(np.uint16(479), np.uint16(0))
(479, 318) (0, 0)
(np.uint16(479), np.uint16(0))
(479, 318) (0, 0)
(np.uint16(479), np.uint16(0))
(479, 318) (0, 0)


C:\Users\georg\AppData\Local\Temp\ipykernel_21924\3489857677.py:3: RuntimeWarning: overflow encountered in scalar subtract
  if yR[1] - yL[1] < MIN_ROAD_WIDTH:


(np.uint16(479), np.uint16(0))
(479, 319) (0, 0)
(np.uint16(479), np.uint16(0))
(479, 318) (0, 0)
(np.uint16(479), np.uint16(0))
(479, 318) (0, 0)
(np.uint16(479), np.uint16(0))
(479, 317) (0, 0)
(np.uint16(479), np.uint16(0))
(479, 319) (0, 0)
(np.uint16(479), np.uint16(0))
(479, 319) (0, 0)
(np.uint16(479), np.uint16(0))
(479, 319) (0, 0)
(np.uint16(479), np.uint16(0))
(479, 317) (0, 0)
(np.uint16(479), np.uint16(0))
(479, 317) (0, 0)
(np.uint16(479), np.uint16(0))
(479, 319) (0, 0)
